name: Deploy MkDocs site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install MkDocs
        run: |
          pip install mkdocs-material

      - name: Build and deploy
        run: |
          mkdocs gh-deploy --force


